config/routes.rb
Rails.application.routes.draw do
  resources :scores
  root 'scores#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
  MAX_POINTS = 3126
  validates :date, :username, :uid, :points, presence:true

  def self.ranking
    self.select("uid, username, sum(points) as points")
      .group("uid, username")
      .order("points DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.ranking
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  private
  def set_score
    @score = Score.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DitoProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/index.html.erb
<div>
  <h2 class="text-center">Dito Challenge</h2>
</div>
<div class="col-md-6 col-md-offset-3">
  <p id="notice"><%= notice %></p>
  <h2>Score</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Uid</th>
        <th>Username</th>
        <th>Points</th>
      </tr>
    </thead>

    <tbody>
      <% @scores.each do |score| %>
        <tr>
          <th class="row"><%= score.uid %></th>
          <td><%= score.username %></td>
          <td><%= score.points %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @score.uid %>
</p>

<p>
  <strong>Username:</strong>
  <%= @score.username %>
</p>

<p>
  <strong>Points:</strong>
  <%= @score.points %>
</p>

<p>
  <strong>Date:</strong>
  <%= @score.date %>
</p>

<%= link_to 'Back', scores_path %>